packages:
  - "apps/*/*"
  - "packages/*"

catalog:
  "@biomejs/biome": 2.4.0
  "@types/node": 24.12.2
  prettier: 3.4.2
  typescript: 5.8.3
  yaml: 2.9.0

catalogMode: prefer

engineStrict: true

minimumReleaseAge: 1440

preferWorkspacePackages: true

strictDepBuilds: true

trustPolicy: no-downgrade

supportedArchitectures:
  os:
    - current
    - linux
    - darwin
    - win32
  cpu:
    - current
    - x64
    - arm64
